#include <ctype.h>
#include "scanner.h"

char lexema[200];

enum estados {
    INICIAL,
    RECON_ID,
    RECON_CONST,
    ARRANCA_CERO,
    RECON_HEXA,
    RECON_CONST_MAL,
    ID_OK,
    CONST_OK,
    HEXA_OK,
    FDT_OK,
    ERR_CONST_MAL,
    RECON_ERR_GRAL,
    ERR_GRAL,
    ESCAPE
};

enum estados TABLA_TRANSICION[13][8] = {
    {ARRANCA_CERO, RECON_CONST, RECON_ID, RECON_ID, RECON_ID, FDT_OK, INICIAL, RECON_ERR_GRAL},
    {RECON_ID, RECON_ID, RECON_ID, RECON_ID, RECON_ID, ID_OK, ID_OK, ID_OK},
    {RECON_CONST, RECON_CONST, RECON_CONST_MAL, RECON_CONST_MAL, RECON_CONST_MAL, CONST_OK, CONST_OK, CONST_OK},
    {RECON_CONST, RECON_CONST, RECON_CONST_MAL, RECON_HEXA, RECON_CONST_MAL, CONST_OK, CONST_OK, CONST_OK},
    {RECON_HEXA, RECON_HEXA, RECON_HEXA, HEXA_OK, HEXA_OK, HEXA_OK, HEXA_OK, HEXA_OK},
    {RECON_CONST_MAL, RECON_CONST_MAL, RECON_CONST_MAL, RECON_CONST_MAL, RECON_CONST_MAL, ERR_CONST_MAL, ERR_CONST_MAL, ERR_CONST_MAL},
    {ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE},
    {ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE},
    {ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE},
    {ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE},
    {ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE},
    {ERR_GRAL, ERR_GRAL, ERR_GRAL, ERR_GRAL, ERR_GRAL, ERR_GRAL, ERR_GRAL, RECON_ERR_GRAL},
    {ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE, ESCAPE}
};

enum token scanner(void) {
    return ERROR_GRAL;
}
