#ifndef TOKENS_H_INCLUDED
#define TOKENS_H_INCLUDED

enum token {FDT,IDENTIFICADOR,NUMERO,PALABRA_RESERVADA_SALIR,PALABRA_RESERVADA_VAR,MAS_IGUAL,MENOS_IGUAL,POR_IGUAL,DIVIDIDO_IGUAL,NUEVA_LINEA};
// PAREN_IZQ =40, PAREN_DER =41,OP_MULTIPLICACION = 42,OP_SUMA =43,OP_RESTA =45,
// OP_DIV = 47, OP_POTENCIA = 94};

#endif