#ifndef TOKENS_H_INCLUDED
#define TOKENS_H_INCLUDED

enum token {FDT,IDENTIFICADOR,NUMERO,PALABRA_RESERVADA_SALIR,PALABRA_RESERVADA_VAR,MAS_IGUAL,MENOS_IGUAL,POR_IGUAL,DIVIDIDO_IGUAL,NUEVA_LINEA};

#endif
